apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: server
  tagPolicy:
    dateTime:
      format: '20060102150405'
  local:
    useDockerCLI: true
    useBuildkit: true
test:
  - image: server
    structureTests:
      - src/test/docker/file-existence.yaml
      - src/test/docker/metadata.yaml
deploy:
  helm:
    releases:
      - name: yamlschema
        chartPath: .
        values:
          image: server
        imageStrategy:
          helm:
            explicitRegistry: true

profiles:
  - name: prod
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest"
    activation:
      - kubeContext: do-fra1-k8s-hiberbee-dev
