apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.kubernetes-client.io
spec:
  conversion:
    strategy: None
  group: kubernetes-client.io
  names:
    kind: ExternalSecret
    listKind: ExternalSecretList
    plural: externalsecrets
    shortNames:
    - es
    singular: externalsecret
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.lastSync
      name: Last Sync
      type: date
    - jsonPath: .status.status
      name: status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            anyOf:
            - required:
              - data
            - required:
              - dataFrom
            oneOf:
            - properties:
                backendType:
                  enum:
                  - secretsManager
                  - systemManager
            - properties:
                backendType:
                  enum:
                  - vault
              required:
              - vaultRole
              - vaultMountPoint
            - properties:
                backendType:
                  enum:
                  - azureKeyVault
              required:
              - keyVaultName
            properties:
              backendType:
                enum:
                - secretsManager
                - systemManager
                - vault
                - azureKeyVault
                type: string
              data:
                items:
                  properties:
                    key:
                      description: Secret key in backend
                      type: string
                    name:
                      description: Name set for this key in the generated secret
                      type: string
                    property:
                      description: Property to extract if secret in backend is a JSON
                        object
                  required:
                  - name
                  - key
                  type: object
                type: array
              dataFrom:
                items:
                  type: string
                type: array
              key:
                type: string
              keyVaultName:
                type: string
              roleArn:
                type: string
              template:
                description: Template which will be deep merged without mutating any
                  existing fields. into generated secret, can be used to set for example
                  annotations or type on the generated secret
                type: object
              vaultMountPoint:
                type: string
              vaultRole:
                type: string
            type: object
    served: true
    storage: true
