{{- with .Values.ingress }}
{{- if .enabled }}
{{- $name := include "metadata.name" $ }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels: {{ include "metadata.labels" $ | indent 4 }}
  annotations: {{ toYaml .annotations | nindent 4  }}
spec:
  rules: {{ range $i,$value := .hosts }}
    - host: {{ $value.host | quote }}
      http:
        paths:
          - path: "{{ default "/" $value.path }}"
            backend:
              serviceName: {{ $name }}
              servicePort: {{ $.Values.service.name }}  {{ end }}
    {{- if .tls }} # @formatter:on
  tls:
    - secretName: {{ .tls.secretName }}
      hosts: {{ range $i,$value := .hosts }}
        - {{ $value.host | quote }} {{ end }}
  {{- end }}
  {{- end }}
{{- end }}
