apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.name" . }}
  labels: {{ include "metadata.labels" . | indent 4 }}
spec:
  {{- if .Release.IsInstall }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector: {{ include "pod.labels" . | nindent 4 }}
